# Generated by Django 4.1.13 on 2024-04-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('des', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobile_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
                ('price', models.FloatField()),
                ('sale', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(default='mobile', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('des', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_service.category')),
            ],
        ),
    ]
