# Generated by Django 4.1.13 on 2024-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
