# Generated by Django 4.1.13 on 2024-05-09 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_service', '0002_alter_clothes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('des', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('des', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='producer',
            field=models.ForeignKey(default='Việt Nam', on_delete=django.db.models.deletion.CASCADE, to='clothes_service.producer'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='style',
            field=models.ForeignKey(default='Style', on_delete=django.db.models.deletion.CASCADE, to='clothes_service.style'),
        ),
    ]
