# Generated by Django 4.0.1 on 2024-05-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('date_paymented', models.DateField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('status', models.BooleanField()),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_service.paymentmethod')),
            ],
        ),
    ]
